# Generated by Django 4.2.7 on 2023-11-24 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SellInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.CharField(max_length=100)),
                ("description", models.CharField(max_length=255)),
                ("pictures", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="SellValuation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("asking_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("shares", models.IntegerField()),
            ],
        ),
    ]
