# Generated by Django 4.2.7 on 2023-11-24 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sell", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SellValuation",
        ),
        migrations.AddField(
            model_name="sellinfo",
            name="asking_price",
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="sellinfo",
            name="shares",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
