# Generated by Django 4.2.7 on 2023-12-01 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sell", "0002_delete_sellvaluation_sellinfo_asking_price_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sellinfo",
            name="pictures",
            field=models.ImageField(upload_to="sell_pictures"),
        ),
    ]
