# Generated by Django 4.2.7 on 2023-12-01 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sell", "0004_alter_sellinfo_pictures"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sellinfo",
            name="pictures",
        ),
        migrations.AddField(
            model_name="sellinfo",
            name="images",
            field=models.ImageField(
                default="property_images/none/NoImage.jpg", upload_to="property_images"
            ),
        ),
    ]
