# Generated by Django 4.2.7 on 2023-12-01 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sell", "0005_remove_sellinfo_pictures_sellinfo_images"),
    ]

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        default="property_images/none/NoImage.jpg",
                        upload_to="property_images",
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="sellinfo",
            name="images",
        ),
        migrations.AddField(
            model_name="sellinfo",
            name="images",
            field=models.ManyToManyField(related_name="sell_info", to="sell.image"),
        ),
    ]
