# Generated by Django 4.2.7 on 2023-12-02 01:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("sell", "0006_image_remove_sellinfo_images_sellinfo_images"),
    ]

    operations = [
        migrations.CreateModel(
            name="PropertyImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        default="property_images/none/NoImage.jpg",
                        upload_to="property_images",
                    ),
                ),
                ("order", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="PropertyInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.CharField(max_length=100)),
                ("description", models.CharField(max_length=255)),
                ("asking_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("shares", models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name="sellinfo",
            name="images",
        ),
        migrations.DeleteModel(
            name="Image",
        ),
        migrations.DeleteModel(
            name="SellInfo",
        ),
        migrations.AddField(
            model_name="propertyimage",
            name="property_info",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="sell.propertyinfo",
            ),
        ),
    ]
