# Generated by Django 4.2.7 on 2023-12-02 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sell", "0007_propertyimage_propertyinfo_remove_sellinfo_images_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="propertyinfo",
            name="images",
            field=models.ImageField(
                default="property_images/none/NoImage.jpg", upload_to="property_images"
            ),
        ),
        migrations.DeleteModel(
            name="PropertyImage",
        ),
    ]
