# Generated by Django 4.2.7 on 2023-12-02 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("sell", "0008_propertyinfo_images_delete_propertyimage"),
    ]

    operations = [
        migrations.CreateModel(
            name="PropertyImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        default="property_images/none/NoImage.jpg",
                        upload_to="property_images",
                    ),
                ),
                ("order", models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name="propertyinfo",
            name="images",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="sell.propertyimage",
            ),
        ),
    ]
