# Generated by Django 4.2.7 on 2023-12-02 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sell", "0009_propertyimage_alter_propertyinfo_images"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="propertyimage",
            name="order",
        ),
    ]
