# Generated by Django 4.2.7 on 2023-12-02 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("sell", "0011_rename_image_propertyimage_images"),
    ]

    operations = [
        migrations.AlterField(
            model_name="propertyinfo",
            name="images",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="sell.propertyimage",
            ),
        ),
    ]
