# Generated by Django 4.2.7 on 2023-12-02 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("sell", "0014_remove_propertyinfo_images_propertyimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="propertyimage",
            name="property_info",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="image",
                to="sell.propertyinfo",
            ),
        ),
    ]
