# Generated by Django 4.2.7 on 2023-12-02 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sell", "0018_alter_propertyimage_property_info"),
    ]

    operations = [
        migrations.AddField(
            model_name="propertyimage",
            name="description",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
