# Generated by Django 5.0 on 2023-12-07 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sell", "0020_propertyinfo_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="propertyinfo",
            old_name="user",
            new_name="username",
        ),
    ]
