# Generated by Django 5.0 on 2023-12-07 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sell", "0021_rename_user_propertyinfo_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="propertyinfo",
            name="username",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
