version: "3.8" 
services:  
  app: 
    build: . 
    volumes:
      - .:/app/ # mount apps to this docker image
    ports:
      - 8000:8000 # map port 8000 to 8000 
    image: application:accretionbackend 
    depends_on:
      - db
    command: ["gunicorn", "--bind", "0.0.0.0:8000", "django_api_accretion.wsgi:application"] #bind all IP address 0.0.0.0 to the port 8000 
  db: 
      image: postgres 
      environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      ports:
        - "5432:5432"
      # volumes:
      #   - pgdata:/var/lib/postgresql/data