# Generated by Django 5.0.3 on 2024-03-24 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DeedRecords",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.CharField(max_length=255)),
                ("street_name", models.CharField(max_length=255)),
                ("street_nuber", models.CharField(max_length=255)),
                ("town", models.CharField(max_length=255)),
                ("type", models.CharField(max_length=255)),
                ("book_page", models.CharField(max_length=255)),
            ],
        ),
    ]
