# Generated by Django 5.0.3 on 2024-05-23 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database_visualization", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="propertydata",
            name="address",
            field=models.CharField(default="NA", max_length=255),
            preserve_default=False,
        ),
    ]
