# Generated by Django 5.0.3 on 2024-05-23 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("database_visualization", "0002_propertydata_address"),
    ]

    operations = [
        migrations.RenameField(
            model_name="propertydata",
            old_name="address",
            new_name="query_string",
        ),
    ]
