# Generated by Django 5.0.3 on 2024-05-25 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database_visualization", "0003_rename_address_propertydata_query_string"),
    ]

    operations = [
        migrations.AddField(
            model_name="propertydata",
            name="imageLink",
            field=models.URLField(blank=True, null=True),
        ),
    ]
