# docker-compose for production environment 

version: "3.8" 
services:  
  app: 
    build: . 
    restart: always 
    volumes:
      - ./django_api_accretion:/django_api_accretion/ # map the project folder to the docker image ## only for development 
      - ./django_api_accretion/media:/vol/web/media/  
      - ./django_api_accretion/static:/vol/web/static/
    ports:
      - 8000:8000 # map port 8000 to 8000 
    image: application:accretionbackend     
    command: ["gunicorn", "--bind", "0.0.0.0:8000", "django_api_accretion.wsgi:application"] #bind all IP address 0.0.0.0 to the port 8000 
    env_file:
      - ./.env 
    environment:
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY} 
      - DEBUG=0
      - ENVIRONMENT=production
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    depends_on:
      - db
  
  db: 
      image: postgres 
      environment:
        - POSTGRES_DB=${DB_NAME}
        - POSTGRES_USER=${DB_USER}
        - POSTGRES_PASSWORD=${DB_PASSWORD} 
      ports:
        - "5432:5432"
      # volumes:
      #   - postgres_data:/var/lib/postgresql/data 
  
  nginx: 
    image: nginx:latest 
    ports: 
      - "80:80" 
    volumes: 
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf # Mount Nginx configuration file
      - ./django_api_accretion/static:/vol/web/static  # Mount static files directory
    depends_on:
      - app 

volumes: 
  postgres: 